### ISSUE TITLE
作者，现在支持STM32了吗？

### ISSUE THREAD

**Issue by Dreamskya** [WallBreakerX/mcu_firmware_writing_via_androidphone#1]

**Comment by WallBreakerX** [comment]
你好，还没有支持32。
没想到这个项目有人关注了，什么时候有空了会试着添加32的支持。

**Comment by Dreamskya** [comment]
你好，添加32，主要与目前的工程，需要添加些什么呢？解析部分吗？刚接触这块，正准备做个工具方便下~

**Comment by WallBreakerX** [comment]
因为项目已经支持了手机与单片机的数据收发，所以理论上只需要修改ISP协议部分的代码就好了。

目前支持的是NXP LPC8xx系列的ISP协议，参考LPC8xx手册的ISP章节：https://studio.segger.com/packages/LPC800/CMSIS/Documents/UM10601.pdf

所以要支持32只需要根据32的ISP协议来发送/接收指令即可，参考：
官方文档 《STM32™ 自举程序中 使用的 USART 协议》https://www.stmcu.org.cn/document/detail/index/id-200191
https://blog.csdn.net/emmy_kanly/article/details/79755654

**Comment by Dreamskya** [comment]
好的，谢谢
